site_name: Omnichannel Nubitel
site_description: Documentation Omnichannel.
site_author: Amirul M
site_favicon: favicon.ico

plugins:
    - search

pages:
    - Inbound: "index.md"
    - About: "about.md"

theme_dir: "custom"

shortcuts:
    help: 72 # h (help)
    next: 83 # s (suivant)
    previous: 80 # p (précédent)
    search: 82 # r (rechercher)

markdown_extensions:
    - admonition

copyright: © Copyright 2023, Nubitel.
